server {
    listen 80;
    server_name seudominio.com.br www.seudominio.com.br;

    root /var/www/regis-imobiliaria;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|pdf)$ {
        expires 7d;
        add_header Cache-Control "public";
    }
}
